#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

app_santa_draw:
    path: /santa/draw
    controller: App\Controller\SantaController::draw

app_new_entrant:
    path: /entrant/create
    controller: App\Controller\EntrantController::create
